language: perl6
perl6:
  - '2019.03'
  - '2018.10'
  - '2018.06'
  - latest
install:
  - rakudobrew build-zef
  - zef install --depsonly .
script:
  - prove -v -e "perl6 --ll-exception -Ilib" -r t
after_success:
  - zef list --installed --verbose
